### ISSUE TITLE
querysort corrupts certain URLs

### ISSUE THREAD

**Issue by carlalexander** [mattiasgeniar/varnish-4.0-configuration-templates#12]
I stumbled on an [issue](http://stackoverflow.com/questions/29929164/issue-with-wordpress-and-varnish-breaking-loadscript-php/30744507) today where `querysort` was corrupting the URL and truncating them.

I'm not super familiar with the VCL language. I was wondering if there was a way we could check that `querysort` isn't corrupting a URL before replacing it. Maybe something simple like a length check?

**Comment by mattiasgeniar** [comment]
I've actually had this exact same experience a couple of times with `querysort`. I suggest you post something on the mailing list in order to help get this resolved?
