### ISSUE TITLE
why is return(fetch) working within vcl_hit?

### ISSUE THREAD

**Issue by adiakritos** [mattiasgeniar/varnish-4.0-configuration-templates#13]
From the 4.0 docs it doesn't show that as a valid termination keyword, and the 3.0 docs say it's to be deprecated. 

I'm guessing that the fetch keyword is still refreshing the content like the 3.0 documentation says.

**Comment by mattiasgeniar** [comment]
Very good point, updated the main VCL to reflect this. Thanks!
