### ISSUE TITLE
Error 503 Backend fetch failed

### ISSUE THREAD

**Issue by dinhkhanh** [mattiasgeniar/varnish-4.0-configuration-templates#15]
I replace default default.vcl by your file.
Then I visit website, it says:

Error 503 Backend fetch failed
Backend fetch failed
Guru Meditation:
XID: 3
Varnish cache server

How to deal with this?

---------------------
My webserver architecture is: Haproxy:80 => Varnish:6081 => Nginx:82
Before that, I use: Haproxy:80 => Nginx:82 (working fine)

**Comment by dinhkhanh** [comment]
This is output of varnishlog


*   << Request  >> 32773     
-   Begin          req 32772 restart
-   Timestamp      Start: 1435311588.546300 0.000230 0.000000
-   ReqStart       127.0.0.1 11847
-   ReqMethod      GET
-   ReqURL         /favicon.ico
-   ReqProtocol    HTTP/1.1
-   ReqHeader      Connection: keep-alive
-   ReqHeader      Pragma: no-cache
-   ReqHeader      Cache-Control: no-cache
-   ReqHeader      User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36
-   ReqHeader      Accept: */*
-   ReqHeader      Referer: http://xxx.com/
-   ReqHeader      Accept-Language: en-US,en;q=0.8,ja;q=0.6,vi;q=0.4
-   ReqHeader      X-Forwarded-For: 127.0.0.1, 127.0.0.1
-   ReqHeader      Host: xxx.com
-   ReqHeader      Accept-Encoding: gzip
-   ReqHeader      X-Purge: Yes
-   VCL_call       RECV
-   ReqUnset       Host: xxx.com
-   ReqHeader      Host: xxx.com
-   ReqURL         /favicon.ico
-   ReqHeader      Cookie: 
-   ReqUnset       Cookie: 
-   ReqHeader      Cookie: 
-   ReqUnset       Cookie: 
-   ReqHeader      Cookie: 
-   ReqUnset       Cookie: 
-   ReqHeader      Cookie: 
-   ReqUnset       Cookie: 
-   ReqHeader      Cookie: 
-   ReqUnset       Cookie: 
-   ReqHeader      Cookie: 
-   ReqUnset       Cookie: 
-   ReqHeader      Cookie: 
-   ReqUnset       Cookie: 
-   ReqHeader      Cookie: 
-   ReqUnset       Cookie: 
-   ReqHeader      Cookie: 
-   ReqUnset       Cookie: 
-   ReqHeader      Cookie: 
-   ReqUnset       Cookie: 
-   ReqHeader      Cookie: 
-   ReqUnset       Cookie: 
-   ReqUnset       Accept-Encoding: gzip
-   ReqHeader      Accept-Encoding: gzip
-   VCL_return     hash
-   VCL_call       HASH
-   VCL_return     lookup
-   Debug          "XXXX MISS"
-   VCL_call       MISS
-   VCL_return     fetch
-   Link           bereq 32774 fetch
-   Timestamp      Fetch: 1435311588.546697 0.000626 0.000396
-   RespProtocol   HTTP/1.1
-   RespStatus     503
-   RespReason     Backend fetch failed
-   RespHeader     Date: Fri, 26 Jun 2015 09:39:48 GMT
-   RespHeader     Server: Varnish
-   RespHeader     Content-Type: text/html; charset=utf-8
-   RespHeader     Retry-After: 5
-   RespHeader     X-Varnish: 32773
-   RespHeader     Age: 0
-   RespHeader     Via: 1.1 varnish-v4
-   VCL_call       DELIVER
-   RespHeader     X-Cache: MISS
-   RespHeader     X-Cache-Hits: 0
-   RespUnset      Server: Varnish
-   RespUnset      X-Varnish: 32773
-   RespUnset      Via: 1.1 varnish-v4
-   VCL_return     deliver
-   Timestamp      Process: 1435311588.546882 0.000811 0.000185
-   RespHeader     Content-Length: 282
-   Debug          "RES_MODE 2"
-   RespHeader     Connection: keep-alive
-   Timestamp      Resp: 1435311588.547010 0.000940 0.000129
-   Debug          "XXX REF 1"
-   ReqAcct        414 0 414 215 282 497
-   End

**Comment by dinhkhanh** [comment]
It works now.
I remove this from backend server1 then it works.

```
.probe = {
    #.url = "/"; # short easy way (GET /)
    # We prefer to only do a HEAD /
    .request =
      "HEAD / HTTP/1.1"
      "Host: localhost"
      "Connection: close";

    .interval  = 5s; # check the health of each backend every 5 seconds
    .timeout   = 1s; # timing out after 1 second.
    .window    = 5;  # If 3 out of the last 5 polls succeeded the backend is considered healthy, otherwise it will be marked as sick
    .threshold = 3;
  }
```

**Comment by mattiasgeniar** [comment]
Sorry for the late reply, just to clarify: those probes indeed tried to validate your backend, which probably didn't respond to those probes with a correct response.

It therefore considered your backend as "sick" and couldn't serve traffic to it.

**Comment by apintocr** [comment]
I know this is closed, but I'm having the same issue and just removing these checks do not make me happy.

@mattiasgeniar could oyu kindly help me troubleshoot what is causing my backend to be "sick"?
I'm very new to Varnish and this is confusing me :)

**Comment by mattiasgeniar** [comment]
@apintocr : the first try should be to run your healtcheck from the varnish server, and see which response you got.

```
$ curl -i 12.23.34.45 -H "Host: yourdomain.tld" -H "Connection: close"
```

Replace the IP with your backend server and the headers with everything from your probe definition. You should get a ``` HTTP 200 OK``` response.

**Comment by denics** [comment]
Hi guys, I know this is closed, but if you have this error, the point is not to disable the "probe" section, but to tweak the values. In my VM that I use as a LAMP test server, a timeout of 1s is too low. With timeout at 5s, everything works as expected (almost, I still have to optimize Drupal).

**Comment by gopinath93** [comment]
Hi guys,
I am using ubuntu LTS and nginx server. I have installed varnish. if i run "varnishstat" in terminal. it is showing some process. I am new to varnish. I am trying to install in localhost. is it possible?

Can u help me guys? I am working on it for 2 days but no response. getting the same error :

Error 503 Backend fetch failed

Backend fetch failed
Guru Meditation:

XID: 3

Varnish cache server

**Comment by jeffryang24** [comment]
Still have the same problem... Error 503...

**Comment by mattiasgeniar** [comment]
This has nothing to do with this configuration. It just means your backend is not responding (correctly) with what you had configured  in the default.vcl.

Please show me the relevant `varnishlog` output of a request that's throwing a 503 response.

**Comment by mpchadwick** [comment]
We were running into this issue as well - getting intermittent 503s from Pingdom / New Relic. Rather than deleting the probe we increased the timeout from 1s to 2s. At this point it *looks* like it's resolved. A 1 second timeout on the probe may be too tight for many websites.

**Comment by daniyel** [comment]
Hi.

Sorry for posting in the closed topic, but... I am also having the same 503 error. When I try my probe settings with curl I am getting 200 response.

```
curl -i HOST:PORT/status -H "Host: my_host" -H "Connection: close" -H "User-Agent: Varnish Health Probe"
```

Response with curl:

```
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET,PUT,POST,PATCH,DELETE,OPTIONS
Content-Type: application/json
Content-Length: 58
Date: Mon, 31 Oct 2016 15:18:24 GMT
Connection: close

{"_links":{"self":{"href":"/status"}},"message":"All OK!"}
```


and the vcl it is default 4.0 config file I just changed the backend values:

````
backend my_host {
  .host = "HOST";
  .port = "PORT";
  .max_connections = 300;
  .probe = {
        .request =
            "GET /status HTTP/1.1"
            "Host: my_host"
            "Connection: close"
            "User-Agent: Varnish Health Probe";
        .timeout   = 5s;
        .interval  = 30s;
        .window    = 5;
        .threshold = 3;
    }
  .first_byte_timeout     = 300s;
  .connect_timeout        = 5s;
  .between_bytes_timeout  = 2s;
}
```

varnishlog does not show anything ^_^.

Best regards.

**Comment by mattiasgeniar** [comment]
Please provide the output of;

```
$ varnishadm -S /etc/varnish/secret -T localhost:6082 debug.health
$ varnishadm -S /etc/varnish/secret -T localhost:6082 backend.list
```

**Comment by daniyel** [comment]
Hi.

I have started varnish without `-S` option, but when i try varnishadm `varnishadm -T :6082 debug.health`, I get `Authentication required` response. I have checked in the /etc/varnish there is no secret file in there. I am installing varnish on Alpine Linux in Docker Container. Can I recreate secret file?

**Comment by daniyel** [comment]
So I managed to recreate secret file with `echo -n "somevarnishsecret" | sha256sum | cut -d ' ' -f 1 > /etc/varnish/secret` and then i tried with `varnishadm -T 0.0.0.0:6082 -S /etc/varnish/secret debug.health` and got 

```
101        
Unknown request.
Type 'help' for more info.

```

for `varnishadm -T 0.0.0.0:6082 -S /etc/varnish/secret backend.list` i get

```
200        
Backend name                   Admin      Probe
boot.my_host        probe      Sick 0/5
```

**Comment by mattiasgeniar** [comment]
Okay, that indeed confirms that Varnish still considers the backend as down.

Since you mention starting Varnish in Docker, what's your networking model? Bridged or host networking? Because that'll make a difference if Varnish can access that backend IP you mentioned or not.

(ref: [example of host-networking mode in Docker](https://ma.ttias.be/run-nginx-proxy-docker-container-http2/))

**Comment by daniyel** [comment]
We have all our Containers on Bridge.

**Comment by mattiasgeniar** [comment]
And you've taken into account that a "curl" check on the host uses different IPs than the ones configured in Varnish, as that has the use the bridge networking?

Varnish considers your backend as down: you should be able to test from within that Docker container (using the Bridge networking) if you can connect to your backends from there.

**Comment by mikelolasagasti** [comment]
@daniyel Just to eliminate variables, are you using CentOS or alike to host Varnish? If so, can you disable SELinux (setenforce 0)?

**Comment by daniyel** [comment]
Hi.

@mattiasgeniar I am performing curl directly from container running varnish to another container that is delivering my REST Api endpoints and I am getting 200 with curl. So to clear things up, I execute `curl -i HOST:PORT/status -H "Host: my_host" -H "Connection: close" -H "User-Agent: Varnish Health Probe"` from container running varnish and HOST + PORT are IP and PORT of a container that is running REST Api that I am trying to cache.

@mikelolasagasti We are running on marathon and mesos, i think mesos is running on CoreOS

I already have REST Api running in one container and Database in another and they are communicating with each other without problems.

**Comment by daniyel** [comment]
OK I found what was wrong, in config file, the slash character was encoded 

```
...
.probe = {
        .request =
            "GET /status HTTP/1.1"
            "Host: review_storage_api"
            "Connection: close"
            "User-Agent: Varnish Health Probe";
        .timeout   = 5s;
        .interval  = 30s;
        .window    = 5;
        .threshold = 3;
    }
...
```

it was 

```
...
.probe = {
        .request =
            "GET &#x2F;status HTTP/1.1"
            "Host: review_storage_api"
            "Connection: close"
            "User-Agent: Varnish Health Probe";
        .timeout   = 5s;
        .interval  = 30s;
        .window    = 5;
        .threshold = 3;
    }
...
```
**Note the special encoding of / character in second config example!**

**Comment by mattiasgeniar** [comment]
Nasty one to find, happy see you got it resolved!

**Comment by AbaevTM** [comment]
@mikelolasagasti In my case it was all about SELinux on CentOS 7 , after disabling it everything works nice.

**Comment by mikelolasagasti** [comment]
@AbaevTM just in case it's better to enable this boolean than disabling SELinux: setsebool varnishd_connect_any 1
