### ISSUE TITLE
Is this configuration store for 6 hours?

### ISSUE THREAD

**Issue by rmalenko** [mattiasgeniar/varnish-4.0-configuration-templates#17]
Hi,

It is not a bug, just a question. :)
Does the configuration store cache dynamic content for 6 hours?

Thank you,

**Comment by mattiasgeniar** [comment]
Hi,

It depends on what your backend (apache/nginx/tomcat/...) responds. Varnish will keep the content in Cache for as long as your Cache-Control or Expires headers tell it to.

You can overwrite it, by setting the TTL, but the best/cleanest way to manage this is via the Cache-Control headers your app can send & manipulate.

**Comment by rmalenko** [comment]
Thank you for answer.
Could you prompt me, please? Will this setting overwrite any setting frop PHP wordpress?
```
sub vcl_backend_response {
...
if (!(bereq.url ~ "wp-(login|admin)")) {
        unset beresp.http.set-cookie;
        set beresp.ttl = 96h;
 }
...
```

**Comment by mattiasgeniar** [comment]
That will prevent your WordPress from ever setting cookies, except on the login/admin pages.

That essentially means that the pages will be cached for your 96h TTL. So yes, that'll work.

**Comment by rmalenko** [comment]
Thank you a lot.
