### ISSUE TITLE
Sometime I get URL with http://site.com:8080

### ISSUE THREAD

**Issue by rmalenko** [mattiasgeniar/varnish-4.0-configuration-templates#18]
Hi,

Sometime I am getting URL with http://site.com:8080 
My config is Varnis -> Nginx -> PHP-FPM
Nginx has this string to help port_in_redirect off; 
However, 8080 is still appearing. Could you help me to understand where and what needs to change, please?

**Comment by mattiasgeniar** [comment]
It's most likely triggered by a 301/302 redirect from either Nginx or your PHP application, that appends the :8080 port in the redirect.

Can you trigger this on demand? If so, can you post the output of ```varnishlog``` of that particular request?

The following _should_ prevent this behaviour, but it may be triggered by other causes as well. Try removing the ``ìf``` condition here and let it apply to all your requests?

````
sub vcl_backend_response {
...
  if (beresp.status == 301 || beresp.status == 302) {
    set beresp.http.Location = regsub(beresp.http.Location, ":[0-9]+", "");
  }
```

**Comment by rmalenko** [comment]
Thank you for answer. Could you help me to find out the issue if you have time, please?
Here are my [varnish.log](https://dl.dropboxusercontent.com/u/16852973/varnish.log) and [varnishncsa.log](https://dl.dropboxusercontent.com/u/16852973/varnishncsa.log)

**Comment by mattiasgeniar** [comment]
Sorry for the late reply here ... the only thing I can imagine if there would be a `return (deliver);` before the logic that handles 301/302 HTTP requests.

Did you finally get this solved?
