### ISSUE TITLE
Make Varnish bypass when add_to_cart in Woocommerce

### ISSUE THREAD

**Issue by chromafunk** [mattiasgeniar/varnish-4.0-configuration-templates#23]
On Nginx cache, you can do this to avoid keep on caching when you add something to the cart in Woocommerce : 

Skip cache for WooCommerce query string
```
if ( $arg_add-to-cart != "" ) { 
      set $skip_cache 1;
}
```
Skip cache when WooCommerce cart is not empty
```
if ( $cookie_woocommerce_items_in_cart != "0" ) {	
	set $skip_cache 1;
}
```

How can you do this in Varnish ? With this config, wich was made specifically for Wordpress + Woocommerce, when you add something to cart, cache is not disabled store wide so you get a mix of cached and non cache pages, cart gets emptied : http://pastebin.com/TuYeMtUZ

**Comment by chromafunk** [comment]
I've just realized that the same happens when logging a user. It would be nice that after login, cache is bypassed for the whole session. Do you have any tip on how to achieve this ?

**Comment by mattiasgeniar** [comment]
Usually, this is done by checking the existence of either a session cookie or a special "logged in" cookie. Some kind of code like this;

```
if (req.http.cookie ~ "PHPSESS") {
  # Logged in user (or at least custom content, since PHP session ID exists)
  return (pass);
}
```

But I must admit my WooCommerce experience is lacking, you'll have to figure out the fine details yourself. I'd appreciate a PR if you manage to get it working, though!

**Comment by chromafunk** [comment]
Yeah, I've been in contact with the Varnish mail list too ... I will work on it and report later, thanks !

**Comment by mattiasgeniar** [comment]
I'll go ahead and close this issue, if there are any other remarks I'd love to hear them.
