### ISSUE TITLE
QUESTION - Would these config be appropriate to run along Ghost 

### ISSUE THREAD

**Issue by pascalandy** [mattiasgeniar/varnish-4.0-configuration-templates#25]
You're probably aware of ghost.org & https://github.com/TryGhost

Cheers!
Pascal

**Comment by mattiasgeniar** [comment]
Sure thing: Varnish can cache NodeJS (like Ghost), PHP, Ruby, ... pretty much anything.

**Comment by pascalandy** [comment]
Very cool! Thanks :)
