### ISSUE TITLE
QUESTION - Why is VCL syntax check returning and error in "return (miss)" ?

### ISSUE THREAD

**Issue by hernangarcia** [mattiasgeniar/varnish-4.0-configuration-templates#26]
After copying the configuration and changing just the port  where apache is running, I checked the syntax and varnishd is returning this error:

Message from VCC-compiler:
Expected return action name.
('input' Line 269 Pos 14)
      return (miss);
-------------####--
Running VCC-compiler failed, exited with 2
VCL compilation failed

Can you please help?

The version of Varnish I am running is:

varnishd -V
varnishd (varnish-4.0.2 revision bfe7cd1)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2014 Varnish Software AS

Thanks in advance!!!

**Comment by mattiasgeniar** [comment]
Hi,

A few days ago I made a change to remove deprecated behaviour, but it seems that was incorrect. I've undone it, please check the latest VCL - it should be OK again.

Mattias
