### ISSUE TITLE
varnish config errors in wordpress ERR_INCOMPLETE_CHUNKED_ENCODING 

### ISSUE THREAD

**Issue by majik12345** [mattiasgeniar/varnish-4.0-configuration-templates#30]
using this config there are a couple of pages in wordpress admin like widgets and rss importer admin (both of these well long loader / possible large pages before). That throw the error ERR_INCOMPLETE_CHUNKED_ENCODING in web browser and fail to load.

I'm 100% it is this varnish config file as I have been through everything else nginx/apache/wordpress/php-fpm etc. deactivated all modules, replaced all configs, checked permissions etc etc... It started working again right If I replace this varnish config with a default basic one with just a backend and a couple of lines in recv everything works, no errors.

So what is causing it to throw chunk errors when loading wp-admin/widgets.php with this config.
In the meantime I will comment out bits line by line until I find what part of vcl is causing the fail...

**Comment by majik12345** [comment]
OK, this i've found the answer pretty much straight away. It is the .between_bytes_timeout value 2s is not enough for all the grinding it does loading those particular admin pages.. increasing to 10s the pages load fine....

Maybe some help for somebody who gets same error anyway. :)

**Comment by mattiasgeniar** [comment]
Hi!

Thanks for solving your own problem. :-)

Are there any other issues, or can I go ahead and close this issue? Others with similar problems will eventually find this post via the magic of Google.

Mattias

**Comment by majik12345** [comment]
everything works fine :D
