### ISSUE TITLE
Error 500 on comments url

### ISSUE THREAD

**Issue by antrecu** [mattiasgeniar/varnish-4.0-configuration-templates#37]
Hi,
thanks for sharing your configuration! i just started using it with a Drupal 8 site an everything seems to be working great except for the comments urls, what i mean is for example, a user posts a comment, an admin goes to the admin/content/comments url to see the list of approved/un-approved comments and clicks on any of the links i.e https://example.com/comment/19#comment-19, the server returns an error 500, when visiting the page without using the varnish server but pointing directly to the web-server (apache), the page loads normally with no problems

![screen shot 2017-02-13 at 3 22 50 pm](https://cloud.githubusercontent.com/assets/3374125/22931855/32a881ac-f294-11e6-87cb-d85795361e84.png)

hope you can provide some guide to fix this issue.
thank you!

**Comment by mattiasgeniar** [comment]
I'm going to need a ```varnishlog``` output of such a failed HTTP call, can you provide that?

**Comment by antrecu** [comment]
Hi Matias, thank you for your quick response! sure i have an output! not sure whats really going on, but tracing the issue i found out that disabling the Devel module "fixes" the issue. Seems to be a overflow issue, i also tried changing the workspace_client memory to 512k but no luck, only disabling Devel, lets access the comment pages through varnish

## deamon config
/usr/sbin/varnishd -j unix,user=vcache -F -a :8080 -T 192.168.10.15:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,1G -p workspace_client=512k

## log

LW@req 86 rxreq+PW@Start: 1487082335.510768 0.000000 0.000000)PW@Req: 1487082335.510768 0.000000 0.000000?W@127.0.0.1 48624W@GET
                                                                                                                                W@/comment/19	W@HTTP/1.1W@Host: antrecu.com_W@User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:51.0) Gecko/20100101 Firefox/51.0HW@Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 W@Accept-Language: en-US,en;q=0.5#W@Accept-Encoding: gzip, deflate, br3W@Referer: https://antrecu.com/admin/content/comment�W@Cookie: _ga=GA1.2.1412487976.1487082096; _gat=1; SESS53d00b15e54ebf1b8fffd7fb77bdee4e=fIBoca5xwx7XL2Pb5YusXS60K7axQIUGpdxXANRooyMW@Connection: keep-aliveW@Upgrade-Insecure-Requests: 1W@Cache-Control: max-age=0W@X-Forwarded-Proto: httpsgW@X-SSL-cipher: TLSv1.2/ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AESGCM(128) Mac=AEADW@X-Forwarded-For: 186.4.166.172W@X-Forwarded-For: 186.4.166.172*W@X-Forwarded-For: 186.4.166.172, 127.0.0.1<W@RECVW@Host: antrecu.comW@Host: antrecu.com
                                                           W@/comment/19�W@Cookie: _ga=GA1.2.1412487976.1487082096; _gat=1; SESS53d00b15e54ebf1b8fffd7fb77bdee4e=fIBoca5xwx7XL2Pb5YusXS60K7axQIUGpdxXANRooyM�W@Cookie: _ga=GA1.2.1412487976.1487082096; _gat=1; SESS53d00b15e54ebf1b8fffd7fb77bdee4e=fIBoca5xwx7XL2Pb5YusXS60K7axQIUGpdxXANRooyM�W@Cookie: _ga=GA1.2.1412487976.1487082096; _gat=1; SESS53d00b15e54ebf1b8fffd7fb77bdee4e=fIBoca5xwx7XL2Pb5YusXS60K7axQIUGpdxXANRooyM�W@Cookie: _ga=GA1.2.1412487976.1487082096; _gat=1; SESS53d00b15e54ebf1b8fffd7fb77bdee4e=fIBoca5xwx7XL2Pb5YusXS60K7axQIUGpdxXANRooyM�W@Cookie: _ga=GA1.2.1412487976.1487082096; _gat=1; SESS53d00b15e54ebf1b8fffd7fb77bdee4e=fIBoca5xwx7XL2Pb5YusXS60K7axQIUGpdxXANRooyMaW@Cookie: _gat=1; SESS53d00b15e54ebf1b8fffd7fb77bdee4e=fIBoca5xwx7XL2Pb5YusXS60K7axQIUGpdxXANRooyMaW@Cookie: _gat=1; SESS53d00b15e54ebf1b8fffd7fb77bdee4e=fIBoca5xwx7XL2Pb5YusXS60K7axQIUGpdxXANRooyMYW@Cookie: SESS53d00b15e54ebf1b8fffd7fb77bdee4e=fIBoca5xwx7XL2Pb5YusXS60K7axQIUGpdxXANRooyMYW@Cookie: SESS53d00b15e54ebf1b8fffd7fb77bdee4e=fIBoca5xwx7XL2Pb5YusXS60K7axQIUGpdxXANRooyMYW@Cookie: SESS53d00b15e54ebf1b8fffd7fb77bdee4e=fIBoca5xwx7XL2Pb5YusXS60K7axQIUGpdxXANRooyMYW@Cookie: SESS53d00b15e54ebf1b8fffd7fb77bdee4e=fIBoca5xwx7XL2Pb5YusXS60K7axQIUGpdxXANRooyMYW@Cookie: SESS53d00b15e54ebf1b8fffd7fb77bdee4e=fIBoca5xwx7XL2Pb5YusXS60K7axQIUGpdxXANRooyMYW@Cookie: SESS53d00b15e54ebf1b8fffd7fb77bdee4e=fIBoca5xwx7XL2Pb5YusXS60K7axQIUGpdxXANRooyMYW@Cookie: SESS53d00b15e54ebf1b8fffd7fb77bdee4e=fIBoca5xwx7XL2Pb5YusXS60K7axQIUGpdxXANRooyMYW@Cookie: SESS53d00b15e54ebf1b8fffd7fb77bdee4e=fIBoca5xwx7XL2Pb5YusXS60K7axQIUGpdxXANRooyMYW@Cookie: SESS53d00b15e54ebf1b8fffd7fb77bdee4e=fIBoca5xwx7XL2Pb5YusXS60K7axQIUGpdxXANRooyMYW@Cookie: SESS53d00b15e54ebf1b8fffd7fb77bdee4e=fIBoca5xwx7XL2Pb5YusXS60K7axQIUGpdxXANRooyMYW@Cookie: SESS53d00b15e54ebf1b8fffd7fb77bdee4e=fIBoca5xwx7XL2Pb5YusXS60K7axQIUGpdxXANRooyMYW@Cookie: SESS53d00b15e54ebf1b8fffd7fb77bdee4e=fIBoca5xwx7XL2Pb5YusXS60K7axQIUGpdxXANRooyMYW@Cookie: SESS53d00b15e54ebf1b8fffd7fb77bdee4e=fIBoca5xwx7XL2Pb5YusXS60K7axQIUGpdxXANRooyMYW@Cookie: SESS53d00b15e54ebf1b8fffd7fb77bdee4e=fIBoca5xwx7XL2Pb5YusXS60K7axQIUGpdxXANRooyMYW@Cookie: SESS53d00b15e54ebf1b8fffd7fb77bdee4e=fIBoca5xwx7XL2Pb5YusXS60K7axQIUGpdxXANRooyM"W@Surrogate-Capability: key=ESI/1.0>W@hash#W@Accept-Encoding: gzip, deflate, brW@Accept-Encoding: gzip<W@HASH>W@lookup<W@MISS>W@fetchKW@bereq 88 fetch+PW@Fetch: 1487082337.220999 1.710231 1.710231	W@HTTP/1.1W@200@OK$W@Date: Tue, 14 Feb 2017 14:25:35 GMTW@Server: Apache/2.4.18 (Ubuntu)2W@Cache-Control: must-revalidate, no-cache, private$W@X-Drupal-Dynamic-Cache: UNCACHEABLE$W@Link: </node/6494>; rel="shortlink"-W@Link: </node/6494/delete>; rel="delete-form".0.)W@Link: </node/6494/edit>; rel="edit-form"TTP4W@Link: </node/6494/revisions>; rel="version-history";W@Link: </blog/install-composer-ubuntu-1604>; rel="revision"i+W@Link: </devel/node/6494>; rel="devel-load"h4W@Link: </devel/node/6494/render>; rel="devel-render"<W@Link: </devel/node/6494/definition>; rel="devel-definition"1W@Link: </node/6494/manage_display>; rel="display"0W@Link: </devel/node/6494/solr>; rel="devel-solr"2W@Link: </node/6494/devel/token>; rel="token-devel"K7$W@Link: </node/6494>; rel="shortlink"-W@Link: </node/6494/delete>; rel="delete-form"@)W@Link: </node/6494/edit>; rel="edit-form"rot4W@Link: </node/6494/revisions>; rel="version-history";W@Link: </blog/install-composer-ubuntu-1604>; rel="revision"+W@Link: </devel/node/6494>; rel="devel-load"r4W@Link: </devel/node/6494/render>; rel="devel-render"<W@Link: </devel/node/6494/definition>; rel="devel-definition"1W@Link: </node/6494/manage_display>; rel="display"ga=0W@Link: </devel/node/6494/solr>; rel="devel-solr"2W@Link: </node/6494/devel/token>; rel="token-devel"oy$W@Link: </node/6494>; rel="shortlink"-W@Link: </node/6494/delete>; rel="delete-form"=fI)W@Link: </node/6494/edit>; rel="edit-form"@4W@Link: </node/6494/revisions>; rel="version-history";W@Link: </blog/install-composer-ubuntu-1604>; rel="revision"y+W@Link: </devel/node/6494>; rel="devel-load";4W@Link: </devel/node/6494/render>; rel="devel-render"<W@Link: </devel/node/6494/definition>; rel="devel-definition"1W@Link: </node/6494/manage_display>; rel="display"=fI0W@Link: </devel/node/6494/solr>; rel="devel-solr"2W@Link: </node/6494/devel/token>; rel="token-devel"x7$W@Link: </node/6494>; rel="shortlink"-W@Link: </node/6494/delete>; rel="delete-form"fIB)W@Link: </node/6494/edit>; rel="edit-form"@4W@Link: </node/6494/revisions>; rel="version-history";W@Link: </blog/install-composer-ubuntu-1604>; rel="revision"b+W@Link: </devel/node/6494>; rel="devel-load"x4W@Link: </devel/node/6494/render>; rel="devel-render"<W@Link: </devel/node/6494/definition>; rel="devel-definition"1W@Link: </node/6494/manage_display>; rel="display"XS60W@Link: </devel/node/6494/solr>; rel="devel-solr"2W@Link: </node/6494/devel/token>; rel="token-devel"NRW@X-UA-Compatible: IE=edgeb15W@Content-language: enca5 W@X-Content-Type-Options: nosniffW@X-Frame-Options: SAMEORIGIN'W@Expires: Sun, 19 Nov 1978 05:00:00 GMTU/W@X-Generator: Drupal 8 (https://www.drupal.org)fW@Vary: Accept-EncodingYuW@Content-Encoding: gzip'W@Content-Type: text/html; charset=UTF-8eW@X-Varnish: 87S6W@Age: 0R8W@Via: 1.1 varnish-v4W@out of workspace (req)<W@DELIVER8W@X-Cache: MISSNRW@out of workspace (Req)08W@X-Cache-Hits: 0W@out of workspace (Req)>W@deliver-PW@Process: 1487082337.221068 1.710299 0.000068e4e8W@Accept-Ranges: bytesQIUW@out of workspace (Req) 8W@Transfer-Encoding: chunkedeW@out of workspace (Req)U
																													 W@RES_MODE 88W@Connection: keep-alivebW@out of workspace (Req)PW@workspace_client overflow	W@HTTP/1.13d0W@500@Internal Server Error2P*PW@Resp: 1487082337.221318 1.710549 0.000250CaQW@710 0 710 0 0 0MW@ashroot@

**Comment by mattiasgeniar** [comment]
Looks like your error is ```out of workspace (req)```. I see you've increased the ```workspace_client```, but this seems to be affected by ```sess_workspace``` more.

Try setting ```sess_workspace=262144```, ```http_req_size=131072``` and ```http_req_hdr_len=49152```.

Let me know how that goes!

**Comment by antrecu** [comment]
Hi Mattias, sorry for the late feedback.. I added the config params you mentioned except for the sess_workspace, since it's causing an error on Varnish 4, when restarting the service you get an "Unknown paramenter" error. (more info here: http://stackoverflow.com/questions/26788794/varnish-error-sess-workspace) and the error when accessing the page is still present. I'm pasting the new log for your review if possible:

root@inferno:/var/log# varnishlog -a -w /var/log/varnish/varnish50x.log -q "RespStatus >= 500 or BerespStatus >= 500"
^Croot@inferno:/var/log# cat varnish/varnish50x.log
VSL
   L@req 1 rxreq+P@Start: 1490635253.201174 0.000000 0.000000)P@Req: 1490635253.201174 0.000000 0.000000?@127.0.0.1 52546@GET
                                                                                                                             @/comment/20	@HTTP/1.1@Host: dev.antrecu.com@Connection: keep-alive@Cache-Control: max-age=0@Upgrade-Insecure-Requests: 1�@User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36S@Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8%@Accept-Encoding: gzip, deflate, sdch @Accept-Language: en-US,en;q=0.8�@Cookie: __zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; _ga=GA1.3.1330595453.1479559087@X-Forwarded-Proto: http @X-Forwarded-For: 192.168.10.110 @X-Forwarded-For: 192.168.10.110+@X-Forwarded-For: 192.168.10.110, 127.0.0.1<@RECV
                                @/comment/20"@Surrogate-Capability: key=ESI/1.0�@Cookie: __zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; _ga=GA1.3.1330595453.1479559087�@Cookie: __zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; _ga=GA1.3.1330595453.1479559087�@Cookie: __zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; _ga=GA1.3.1330595453.1479559087�@Cookie: __zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; _ga=GA1.3.1330595453.1479559087�@Cookie: __zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; _ga=GA1.3.1330595453.1479559087�@Cookie: __zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; __atuvc=12%7C6%2C4%7C7; SESS687�@Cookie: __zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; __atuvc=12%7C6%2C4%7C7; SESS687�@Cookie: __zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; __atuvc=12%7C6%2C4%7C7; SESS687�@Cookie: __zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; __atuvc=12%7C6%2C4%7C7; SESS687�@Cookie: __zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; __atuvc=12%7C6%2C4%7C7; SESS687�@Cookie: __zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; __atuvc=12%7C6%2C4%7C7; SESS687�@Cookie: __zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; __atuvc=12%7C6%2C4%7C7; SESS687�@Cookie: __zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; __atuvc=12%7C6%2C4%7C7; SESS687+�@Cookie: __zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; __atuvc=12%7C6%2C4%7C7; SESS687u�@Cookie: __zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; __atuvc=12%7C6%2C4%7C7; SESS687r�@Cookie: __zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; __atuvc=12%7C6%2C4%7C7; SESS687n�@Cookie: __zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; __atuvc=12%7C6%2C4%7C7; SESS687n�@Cookie: __zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; __atuvc=12%7C6%2C4%7C7; SESS687n�@Cookie: __zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; __atuvc=12%7C6%2C4%7C7; SESS687n�@Cookie: __zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; SESS6874cd1170e17534e1947809b31n�@Cookie: __zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; SESS6874cd1170e17534e1947809b31n�@Cookie: __zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; SESS6874cd1170e17534e1947809b31n�@Cookie: __zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; SESS6874cd1170e17534e1947809b31n�@Cookie: __zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; SESS6874cd1170e17534e1947809b31n�@Cookie: __zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; SESS6874cd1170e17534e1947809b31n�@Cookie: ;__zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; SESS6874cd1170e17534e1947809b3n�@Cookie: ;__zlcmid=dgg0qUtEWMLhnx; calltrk_referrer=direct; calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user; calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1; Drupal.tableDrag.showWeight=0; SESS6874cd1170e17534e1947809b3�@Cookie: ;__zlcmid=dgg0qUtEWMLhnx;calltrk_referrer=direct;calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user;calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1;Drupal.tableDrag.showWeight=0;SESS6874cd1170e17534e1947809b31b5f4+�@Cookie: ;__zlcmid=dgg0qUtEWMLhnx;calltrk_referrer=direct;calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user;calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1;Drupal.tableDrag.showWeight=0;SESS6874cd1170e17534e1947809b31b5f4u�@Cookie: ;__zlcmid=dgg0qUtEWMLhnx;calltrk_referrer=direct;calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user;calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1;Drupal.tableDrag.showWeight=0; SESS6874cd1170e17534e1947809b31b5fr�@Cookie: ;__zlcmid=dgg0qUtEWMLhnx;calltrk_referrer=direct;calltrk_landing=http%3A//www.markschneiderdesign.antrecu.com/user;calltrk_session_id_186631921=f21eb789-b9db-4e4b-bec9-8d8e766ad7e1;Drupal.tableDrag.showWeight=0; SESS6874cd1170e17534e1947809b31b5fn�@Cookie: ; SESS6874cd1170e17534e1947809b31b5f4b=H2BdMAWtbF5rR8zcdZnE_908ADcDIb9LuY2ZzBsnq2A; SESS53d00b15e54ebf1b8fffd7fb77bdee4e=OpAvvggycp8hlm-1cssXEReh8RjIU2S7CJxmYGEjgAM;ec�@Cookie: ; SESS6874cd1170e17534e1947809b31b5f4b=H2BdMAWtbF5rR8zcdZnE_908ADcDIb9LuY2ZzBsnq2A; SESS53d00b15e54ebf1b8fffd7fb77bdee4e=OpAvvggycp8hlm-1cssXEReh8RjIU2S7CJxmYGEjgAM;ne�@Cookie: SESS6874cd1170e17534e1947809b31b5f4b=H2BdMAWtbF5rR8zcdZnE_908ADcDIb9LuY2ZzBsnq2A; SESS53d00b15e54ebf1b8fffd7fbK@bereq 3 passu.c+P@Fetch: 1490635254.117329 0.916155 0.916155-@@HTTP/1.1ad7@200@OKo$@Date: Mon, 27 Mar 2017 17:20:53 GMT@Server: Apache/2.4.18 (Ubuntu);2@Cache-Control: must-revalidate, no-cache, privateks$@X-Drupal-Dynamic-Cache: UNCACHEABLE$@Link: </node/6493>; rel="shortlink"-@Link: </node/6493/delete>; rel="delete-form"117)@Link: </node/6493/edit>; rel="edit-form"qUt4@Link: </node/6493/revisions>; rel="version-history"G@Link: </blog/run-php7-fpm-apache-mpmevent-ubuntu-1604>; rel="revision"b+@Link: </devel/node/6493>; rel="devel-load"i4@Link: </devel/node/6493/render>; rel="devel-render"<@Link: </devel/node/6493/definition>; rel="devel-definition"1@Link: </node/6493/manage_display>; rel="display"ion0@Link: </devel/node/6493/solr>; rel="devel-solr"2@Link: </node/6493/devel/token>; rel="token-devel"n$@Link: </node/6493>; rel="shortlink"-@Link: </node/6493/delete>; rel="delete-form"rks)@Link: </node/6493/edit>; rel="edit-form"id_4@Link: </node/6493/revisions>; rel="version-history"G@Link: </blog/run-php7-fpm-apache-mpmevent-ubuntu-1604>; rel="revision"g+@Link: </devel/node/6493>; rel="devel-load"n4@Link: </devel/node/6493/render>; rel="devel-render"<@Link: </devel/node/6493/definition>; rel="devel-definition"1@Link: </node/6493/manage_display>; rel="display"0@Link: </devel/node/6493/solr>; rel="devel-solr"2@Link: </node/6493/devel/token>; rel="token-devel"re$@Link: </node/6493>; rel="shortlink"-@Link: </node/6493/delete>; rel="delete-form"sho)@Link: </node/6493/edit>; rel="edit-form"@4@Link: </node/6493/revisions>; rel="version-history"G@Link: </blog/run-php7-fpm-apache-mpmevent-ubuntu-1604>; rel="revision"o+@Link: </devel/node/6493>; rel="devel-load";4@Link: </devel/node/6493/render>; rel="devel-render"<@Link: </devel/node/6493/definition>; rel="devel-definition"1@Link: </node/6493/manage_display>; rel="display"0@Link: </devel/node/6493/solr>; rel="devel-solr"2@Link: </node/6493/devel/token>; rel="token-devel"n.$@Link: </node/6493>; rel="shortlink"-@Link: </node/6493/delete>; rel="delete-form"Dra)@Link: </node/6493/edit>; rel="edit-form"4@Link: </node/6493/revisions>; rel="version-history"G@Link: </blog/run-php7-fpm-apache-mpmevent-ubuntu-1604>; rel="revision"i+@Link: </devel/node/6493>; rel="devel-load"14@Link: </devel/node/6493/render>; rel="devel-render"<@Link: </devel/node/6493/definition>; rel="devel-definition"1@Link: </node/6493/manage_display>; rel="display"rec0@Link: </devel/node/6493/solr>; rel="devel-solr"2@Link: </node/6493/devel/token>; rel="token-devel"4c@X-UA-Compatible: IE=edge@@Content-language: enhnx @X-Content-Type-Options: nosniff@X-Frame-Options: SAMEORIGIN'@Expires: Sun, 19 Nov 1978 05:00:00 GMTe/@X-Generator: Drupal 8 (https://www.drupal.org)@X-Varnish: 2/ww@Age: 0d8@Via: 1.1 varnish-v4@out of workspace (req)<@DELIVER8@X-Varnish-Cache: MISSsh@out of workspace (Req)42@Cache-Control: must-revalidate, no-cache, private78D@Cache-Control: no-cache, must-revalidate, post-check=0, pre-check=08@X-Cache-Hits: 0@out of workspace (Req)>@deliver-P@Process: 1490635254.117391 0.916216 0.000062Wtb8@Accept-Ranges: bytessnq@out of workspace (Req)b8@Transfer-Encoding: chunkedj@out of workspace (Req)k
                                                                                       @RES_MODE 818@Connection: keep-alive5@out of workspace (Req)A@workspace_client overflowee	@HTTP/1.1-1c@500@Internal Server ErrorML*P@Resp: 1490635254.117642 0.916467 0.000251>Q@955 0 955 0 0 0M@u.c

![varnish-status](https://cloud.githubusercontent.com/assets/3374125/24369114/9363ba6a-12e8-11e7-9025-16740424c056.png)


Thank you!!!

**Comment by mattiasgeniar** [comment]
Ow, Varnish 4, my bad. Please add the following;

```
             -p http_req_size=32768 \
             -p http_req_hdr_len=8192
```

Increase those values as you debug, they determine;

```
http_req_size: Maximum number of bytes of HTTP client request we will deal with.
http_req_hdr_len: Maximum length of any HTTP client request header we will allow. The limit is inclusive its continuation lines.
```

**Comment by antrecu** [comment]
Hi Mattias! thanks once again for your support!

unfortunately i can't get rid of this weird issue, i've tried multiple combinations on the parameters you suggested and included other combinations as well to see if that might fix the issue. i tried combinations like this one for example:

-p workspace_client=4096k \
-p workspace_backend=4096k
-p http_req_size=64000 \
-p http_req_hdr_len=32000 \
-p feature=+esi_disable_xml_check

but no matter what values you set for the varnish daemon theres no way to access the /comment/19#comment-19 URL on this specific Drupal 8 site (lets call it site A).

I tried on a new Drupal 8 install ( fresh install, lets call it site B ) with similar Drupal modules enabled as site A and with a standard daemon params for varnish:

-p workspace_client=512k \
-p feature=+esi_disable_xml_check

and the comments url (i.e comment/19#comment-19) on site B is completely accesible! Which makes me think that is either a some sort of combination of modules on site A that break varnish no matter what configuration you set for the deamon ( which makes no much sense ) or is a Varnish 4.1 bug on the Ubuntu package.
Apparently this issue is already reported on the varnish community, https://www.varnish-cache.org/lists/pipermail/varnish-misc/2016-February/024837.html
I'll keep looking into this and get back to you if i can find a solution. On the other hand your VCL config is working great!

if you have the time eventually to go over this, here's the guide i followed (which includes your vcl) to setup the environment where im doing my tests, 
https://antrecu.com/blog/advanced-drupal-8-cache-pound-varnish-4-ubuntu

Thank you!!

Andres.

**Comment by fiasco** [comment]
I used [this patch for Drupal 8](https://www.drupal.org/node/2861552) to help get around this problem (though I'd like to know how to get Varnish to handle this).

**Comment by mattiasgeniar** [comment]
I don't think Varnish will ever handle this, it adheres to the HTTP protocol, and those duplicate headers violate that protocol. Only (*) the `Set-Cookie` header is allowed to be duplicate.

The only fix is in the code, which you did: you should be good now. :-)

(*) Could be more, but I doubt it.

**Comment by cherouvim** [comment]
Sovled it with `-p http_max_hdr=256`. Default is 64 and that was not enough.
