### ISSUE TITLE
Getting Always (X-Cache: MISS)

### ISSUE THREAD

**Issue by theraw** [mattiasgeniar/varnish-4.0-configuration-templates#46]
Hello i've just copy and paste your configuration and i've just change backend ip/port.
As of info : My backend isn't in the same server where varnish is installed apache is in a different server and varnish is in a different server.
I'm asking here as i'm very new with varnish this is my first time working with it and i hope someone from here can gave some help about this.

So as i said i've just copy and paste your configuration but idk why i always get this output
```
< HTTP/1.1 200 OK
< Date: Thu, 02 Nov 2017 21:10:56 GMT
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Pragma: no-cache
< Set-Cookie: PHPSESSID=ko7urmd74ar9v6ej6ghambs1h0; path=/; HttpOnly
< Content-Type: text/html; charset=UTF-8
< Age: 0
< X-Cache: MISS
< X-Cache-Hits: 0
< Accept-Ranges: bytes
< Content-Length: 8229
< Connection: keep-alive
```

Can someone help about this?
Thanks.

**Comment by mattiasgeniar** [comment]
Your problem is here;

```
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
```

Your backend (aka: your web application) responds with a "no-cache" header. Tell your application to set the right headers, and Varnish will honour them & cache the page.

**Comment by mattiasgeniar** [comment]
Additionally, your webapp is setting a PHP Session ID cookie on this request, which is probably what triggers the `no-cache` in the first place.

```
Set-Cookie: PHPSESSID=ko7urmd74ar9v6ej6ghambs1h0; path=/; HttpOnly

**Comment by theraw** [comment]
thank you for information
