### ISSUE TITLE
ReqMethod PURGE ends up with VCL_Error Too many restarts

### ISSUE THREAD

**Issue by mojzis** [mattiasgeniar/varnish-4.0-configuration-templates#5]
i think there is a slight issue where the vcl_purge does return(restart) - it should probably do so only in case req.method != "PURGE" - for the CTRL-F5 case ... because it probably doesn't make much sense to restart a purge. And since in the other part that invokes purge there is no check for restarts, nor for the header, this causes errors :)

**Comment by mattiasgeniar** [comment]
I haven't tested this, but I'm fairly sure CTRL+F5 smashing wouldn't invoke the vcl_purge() call?

**Comment by mojzis** [comment]
@mattiasgeniar thats what you have here - only for users from IPs allowed to do so:
https://github.com/mattiasgeniar/varnish-4.0-configuration-templates/blob/master/default.vcl#L172
(and down to line 178)
but the problem for me is that in vcl_purge there is the restart, so when we do a "real" PURGE rewuest, we end up in a cycle -> thats why there is the condition (should be != - sorry, i only did it in the second commit)

**Comment by mattiasgeniar** [comment]
Aha, now I understand. Thanks for this, it's been merged!
