### ISSUE TITLE
This template allow anyone to purge you cache

### ISSUE THREAD

**Issue by obriat** [mattiasgeniar/varnish-4.0-configuration-templates#52]
This template is dangerous !!!

The following code allow anyone to purge all you cache and empty you "grace cache" if you backends are down.
https://github.com/mattiasgeniar/varnish-4.0-configuration-templates/blob/989cd0cfa32f62943cb57871503e616988d064a8/default.vcl#L155
You just have to set "no cache" in you browser developer tools and starting navigate your web site.
Remove theses line or set the "editors" acl.

**Comment by mattiasgeniar** [comment]
Agree, this should have been given a better warning, commented it out now.

For reference: this VCL is end of life, please use only varnish 6.x or higher.

**Comment by obriat** [comment]
Thanks, I was afraid I didn't understand correctly your template. 
We're still have a some old Varnish 4 in front of legacy drupal... and at that time your template was heavily used :)
