### ISSUE TITLE
Is X-Forwarded-For code redundant?

### ISSUE THREAD

**Issue by phil-lavin** [mattiasgeniar/varnish-4.0-configuration-templates#8]
On Varnish 4.0, this code seems to duplicate the client IP into the header so it appears twice.

https://github.com/mattiasgeniar/varnish-4.0-configuration-templates/blob/master/default.vcl#L58

Is it now a default feature of Varnish?

**Comment by mattiasgeniar** [comment]
I'll have to test this and get back to you, thanks for reporting!

**Comment by frantzz** [comment]
Hi mattiasgeniar, so you have any informations about that ?
"Is it now a default feature of Varnish?"

**Comment by jonathantullett** [comment]
I've tested this and it does appear to be a default feature in varnish 4,0 (I'm using 4.0.3), so the rules to add them can be removed.

**Comment by frantzz** [comment]
Great, thank you.

**Comment by LukeHandle** [comment]
This can now be closed off as per #19

**Comment by mattiasgeniar** [comment]
Much appreciated everyone, issue now closed.
