### ISSUE TITLE
Getting the wrong content from varnish

### ISSUE THREAD

**Issue by Hoet** [mattiasgeniar/varnish-4.0-configuration-templates#9]
Varnish delivers the wrong content for a number of page. I can't lay my finger on the pattern. When you do a CTRL-F5 the right content is returned. I have been searching on the internet for a solution to this, but I have not been able to find one.

Set-up:
1 core varnish server debian 7.8, 16Gb disk, 1G mem
8 core content server debian 7.8, 64Gb disk, 64Gb mem, plesk 12, php-fpm, nginx, APC

Website:
Joomla with user login on the front

Also running an ab -n 1000 -c 50 .... while checking the "varnishtop -c -i ReqURL" and "varnishtop -b -i BereqURL" in two separate putty windows shows that the requests from the front are send to the backend at a rate of 2:1. i.e. for every two requests on the front one request seems to this the back. I would have expected that there would be only one or just a handful or requests to the backend

**Comment by mattiasgeniar** [comment]
Can you post a full varnishlog output of one request (with anonimized host/url)?

What headers are your backend setting on the cache control? Are you using the "default" version of this VCL or have you modified it in any way?

**Comment by Hoet** [comment]
I use the default version. With the modification for the server IP the backend is located on.

I did make some changes based on other posts around the internet to see if I could fix the problem, but nothing worked.

The backend is using a extension to set cache-control in the header "System - Expires Headers"
Caching should be 2 hours based on the setting in the extension

** snip **
vcl 4.0;

import std;
import directors;

backend server1 {
  .host = "85.222.224.212";
  .port = "80";
  .max_connections = 300;

  .probe = {
    #.url = "/"; # short easy way (GET /)
    # We prefer to only do a HEAD /
    .request =
      "HEAD / HTTP/1.1"
      "Host: www.woekerpolisproces.nl"
      "Connection: close";
    .interval = 5s; # check the health of each backend every 5 seconds
    .timeout = 1s; # timing out after 1 second.

    # If 3 out of the last 5 polls succeeded the backend is considered healthy, otherwise it will be marked as sick
    .window = 5;
    .threshold = 3;
  }

  .first_byte_timeout     = 300s;   # How long to wait before we receive a first byte from our backend?
  .connect_timeout        = 5s;     # How long to wait for a backend connection?
  .between_bytes_timeout  = 2s;     # How long to wait between bytes received from our backend?
}

acl purge {
# ACL we'll use later to allow purges
  "localhost";
  "127.0.0.1";
  "85.222.224.212";
  "::1";
}

sub vcl_init {
# Called when VCL is loaded, before any requests pass through it. Typically used to initialize VMODs.

  new vdir = directors.round_robin();
  vdir.add_backend(server1);
  # vdir.add_backend(server...);
  # vdir.add_backend(servern);
}

*********

________________________________

**Comment by Hoet** [comment]
requested url: http://www.woekerpolisproces.nl/woekerpolis/delta-lloyd-woekerpolis
Obtained info from: http://www.woekerpolisproces.nl/nieuws-media/stichting-in-het-nieuws/interview-bnr-nieuws-radio-aegon

*   << BeReq    >> 196798
-   Begin          bereq 196797 fetch
-   Timestamp      Start: 1422798495.239912 0.000000 0.000000
-   BereqMethod    GET
-   BereqURL       /media/widgetkit/widgets/mediaplayer/mediaelement/mediaelement-and-player.js?_=1422798495219
-   BereqProtocol  HTTP/1.1
-   BereqHeader    Accept: text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.01
-   BereqHeader    X-Requested-With: XMLHttpRequest
-   BereqHeader    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.94 Safari/537.36
-   BereqHeader    Referer: http://www.woekerpolisproces.nl/woekerpolis/delta-lloyd-woekerpolis
-   BereqHeader    Accept-Language: en-US,en;q=0.8,nl;q=0.6
-   BereqHeader    X-Forwarded-For: 37.153.217.43, 37.153.217.43
-   BereqHeader    Host: www.woekerpolisproces.nl
-   BereqHeader    Accept-Encoding: gzip
-   BereqHeader    X-Varnish: 196798
-   VCL_call       BACKEND_FETCH
-   VCL_return     fetch
-   BackendClose   19 server1(xxx.xxx.xxx.xxx,,80) toolate
-   BackendClose   21 server1(xxx.xxx.xxx.xxx,,80) toolate
-   BackendClose   26 server1(xxx.xxx.xxx.xxx,,80) toolate
-   BackendOpen    17 server1(xxx.xxx.xxx.xxx,,80) xxx.xxx.xxx.xxx 45735
-   Backend        17 vdir server1(xxx.xxx.xxx.xxx,,80)
-   Timestamp      Bereq: 1422798495.240575 0.000664 0.000664
-   Timestamp      Beresp: 1422798495.243479 0.003568 0.002904
-   BerespProtocol HTTP/1.1
-   BerespStatus   200
-   BerespReason   OK
-   BerespHeader   Server: nginx
-   BerespHeader   Date: Sun, 01 Feb 2015 13:48:15 GMT
-   BerespHeader   Content-Type: application/javascript
-   BerespHeader   Last-Modified: Thu, 29 Jan 2015 21:40:44 GMT
-   BerespHeader   Transfer-Encoding: chunked
-   BerespHeader   Connection: keep-alive
-   BerespHeader   Vary: Accept-Encoding
-   BerespHeader   Expires: Tue, 03 Mar 2015 13:48:15 GMT
-   BerespHeader   Cache-Control: max-age=2592000
-   BerespHeader   Pragma: public
-   BerespHeader   Cache-Control: “public”
-   BerespHeader   Content-Encoding: gzip
-   TTL            RFC 2592000 -1 -1 1422798495 1422798495 1422798495 1425390495 2592000
-   VCL_call       BACKEND_RESPONSE
-   TTL            VCL 2592000 21600 0 1422798495
-   VCL_return     deliver
-   Storage        malloc s0
-   ObjProtocol    HTTP/1.1
-   ObjStatus      200
-   ObjReason      OK
-   ObjHeader      Server: nginx
-   ObjHeader      Date: Sun, 01 Feb 2015 13:48:15 GMT
-   ObjHeader      Content-Type: application/javascript
-   ObjHeader      Last-Modified: Thu, 29 Jan 2015 21:40:44 GMT
-   ObjHeader      Vary: Accept-Encoding
-   ObjHeader      Expires: Tue, 03 Mar 2015 13:48:15 GMT
-   ObjHeader      Cache-Control: max-age=2592000, “public”
-   ObjHeader      Pragma: public
-   ObjHeader      Content-Encoding: gzip
-   Fetch_Body     2 chunked stream
-   Gzip           u F - 17525 63770 80 80 140133
-   BackendReuse   17 server1(xxx.xxx.xxx.xxx,,80)
-   Timestamp      BerespBody: 1422798495.244349 0.004438 0.000870
-   Length         17525
-   BereqAcct      629 0 629 371 17537 17908
-   End

*   << Request  >> 196797
-   Begin          req 196796 rxreq
-   Timestamp      Start: 1422798495.239776 0.000000 0.000000
-   Timestamp      Req: 1422798495.239776 0.000000 0.000000
-   ReqStart       37.153.217.43 51032
-   ReqMethod      GET
-   ReqURL         /media/widgetkit/widgets/mediaplayer/mediaelement/mediaelement-and-player.js?_=1422798495219
-   ReqProtocol    HTTP/1.1
-   ReqHeader      Host: www.woekerpolisproces.nl
-   ReqHeader      Connection: keep-alive
-   ReqHeader      Accept: text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.01
-   ReqHeader      X-Requested-With: XMLHttpRequest
-   ReqHeader      User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.94 Safari/537.36
-   ReqHeader      Referer: http://www.woekerpolisproces.nl/woekerpolis/delta-lloyd-woekerpolis
-   ReqHeader      Accept-Encoding: gzip, deflate, sdch
-   ReqHeader      Accept-Language: en-US,en;q=0.8,nl;q=0.6
-   ReqHeader      Cookie: f9350eb737e0fdef9fddfe414deb5a2c=ajjq2k1a2ull0j23f44aq8onb1; _gat=1; _ga=GA1.2.65084237.1422569390
-   ReqHeader      X-Forwarded-For: xxx.xxx.xxx.xxx
-   VCL_call       RECV
-   ReqUnset       X-Forwarded-For: xxx.xxx.xxx.xxx
-   ReqHeader      X-Forwarded-For: xxx.xxx.xxx.xxx, xxx.xxx.xxx.xxx
-   ReqUnset       Host: www.woekerpolisproces.nl
-   ReqHeader      Host: www.woekerpolisproces.nl
-   ReqURL         /media/widgetkit/widgets/mediaplayer/mediaelement/mediaelement-and-player.js?_=1422798495219
-   ReqUnset       Cookie: f9350eb737e0fdef9fddfe414deb5a2c=ajjq2k1a2ull0j23f44aq8onb1; _gat=1; _ga=GA1.2.65084237.1422569390
-   ReqHeader      Cookie: f9350eb737e0fdef9fddfe414deb5a2c=ajjq2k1a2ull0j23f44aq8onb1; _gat=1; _ga=GA1.2.65084237.1422569390
-   ReqUnset       Cookie: f9350eb737e0fdef9fddfe414deb5a2c=ajjq2k1a2ull0j23f44aq8onb1; _gat=1; _ga=GA1.2.65084237.1422569390
-   ReqHeader      Cookie: f9350eb737e0fdef9fddfe414deb5a2c=ajjq2k1a2ull0j23f44aq8onb1; _gat=1; _ga=GA1.2.65084237.1422569390
-   ReqUnset       Cookie: f9350eb737e0fdef9fddfe414deb5a2c=ajjq2k1a2ull0j23f44aq8onb1; _gat=1; _ga=GA1.2.65084237.1422569390
-   ReqHeader      Cookie: f9350eb737e0fdef9fddfe414deb5a2c=ajjq2k1a2ull0j23f44aq8onb1; _gat=1;
-   ReqUnset       Cookie: f9350eb737e0fdef9fddfe414deb5a2c=ajjq2k1a2ull0j23f44aq8onb1; _gat=1;
-   ReqHeader      Cookie: f9350eb737e0fdef9fddfe414deb5a2c=ajjq2k1a2ull0j23f44aq8onb1; _gat=1;
-   ReqUnset       Cookie: f9350eb737e0fdef9fddfe414deb5a2c=ajjq2k1a2ull0j23f44aq8onb1; _gat=1;
-   ReqHeader      Cookie: f9350eb737e0fdef9fddfe414deb5a2c=ajjq2k1a2ull0j23f44aq8onb1; _gat=1;
-   ReqUnset       Cookie: f9350eb737e0fdef9fddfe414deb5a2c=ajjq2k1a2ull0j23f44aq8onb1; _gat=1;
-   ReqHeader      Cookie: f9350eb737e0fdef9fddfe414deb5a2c=ajjq2k1a2ull0j23f44aq8onb1; _gat=1;
-   ReqUnset       Cookie: f9350eb737e0fdef9fddfe414deb5a2c=ajjq2k1a2ull0j23f44aq8onb1; _gat=1;
-   ReqHeader      Cookie: f9350eb737e0fdef9fddfe414deb5a2c=ajjq2k1a2ull0j23f44aq8onb1; _gat=1;
-   ReqUnset       Cookie: f9350eb737e0fdef9fddfe414deb5a2c=ajjq2k1a2ull0j23f44aq8onb1; _gat=1;
-   ReqHeader      Cookie: f9350eb737e0fdef9fddfe414deb5a2c=ajjq2k1a2ull0j23f44aq8onb1; _gat=1;
-   ReqUnset       Cookie: f9350eb737e0fdef9fddfe414deb5a2c=ajjq2k1a2ull0j23f44aq8onb1; _gat=1;
-   ReqHeader      Cookie: f9350eb737e0fdef9fddfe414deb5a2c=ajjq2k1a2ull0j23f44aq8onb1; _gat=1;
-   ReqUnset       Cookie: f9350eb737e0fdef9fddfe414deb5a2c=ajjq2k1a2ull0j23f44aq8onb1; _gat=1;
-   ReqHeader      Cookie: f9350eb737e0fdef9fddfe414deb5a2c=ajjq2k1a2ull0j23f44aq8onb1; _gat=1;
-   ReqUnset       Accept-Encoding: gzip, deflate, sdch
-   ReqHeader      Accept-Encoding: gzip
-   ReqUnset       Cookie: f9350eb737e0fdef9fddfe414deb5a2c=ajjq2k1a2ull0j23f44aq8onb1; _gat=1;
-   VCL_return     hash
-   VCL_call       HASH
-   VCL_return     lookup
-   Debug          "XXXX MISS"
-   VCL_call       MISS
-   VCL_return     fetch
-   Link           bereq 196798 fetch
-   Timestamp      Fetch: 1422798495.243635 0.003859 0.003859
-   RespProtocol   HTTP/1.1
-   RespStatus     200
-   RespReason     OK
-   RespHeader     Server: nginx
-   RespHeader     Date: Sun, 01 Feb 2015 13:48:15 GMT
-   RespHeader     Content-Type: application/javascript
-   RespHeader     Last-Modified: Thu, 29 Jan 2015 21:40:44 GMT
-   RespHeader     Vary: Accept-Encoding
-   RespHeader     Expires: Tue, 03 Mar 2015 13:48:15 GMT
-   RespHeader     Cache-Control: max-age=2592000, “public”
-   RespHeader     Pragma: public
-   RespHeader     Content-Encoding: gzip
-   RespHeader     X-Varnish: 196797
-   RespHeader     Age: 0
-   RespHeader     Via: 1.1 varnish-v4
-   VCL_call       DELIVER
-   RespHeader     X-Cache: MISS
-   RespHeader     X-Cache-Hits: 0
-   RespUnset      Server: nginx
-   RespUnset      X-Varnish: 196797
-   RespUnset      Via: 1.1 varnish-v4
-   VCL_return     deliver
-   Timestamp      Process: 1422798495.243694 0.003918 0.000060
-   Debug          "RES_MODE 8"
-   RespHeader     Transfer-Encoding: chunked
-   RespHeader     Connection: keep-alive
-   RespHeader     Accept-Ranges: bytes
-   Timestamp      Resp: 1422798495.244412 0.004637 0.000718
-   Debug          "XXX REF 2"
-   ReqAcct        710 0 710 403 17540 17943
-   End

*   << Session  >> 196796
-   Begin          sess 0 HTTP/1
-   SessOpen       37.153.217.43 51032 :80 85.222.225.252 80 1422798495.239366 14
-   Link           req 196797 rxreq
-   SessClose      RX_TIMEOUT 5.083
-   End

________________________________

**Comment by Hoet** [comment]
content server is a 8 core, 64Gb mem.
varnish is a 1core 1G memory

________________________________
